### ISSUE TITLE
Collect 10 Real World Bugs

### ISSUE THREAD

**Issue by alingse** [alingse/sundrylint#1]
I want to collect 10 or 100 real world bugs and try add it to golangci-lint

## TimeParse 

- https://github.com/minio/minio/pull/19279
- https://github.com/bosun-monitor/bosun/pull/2515

## RangeAppendAll

- https://github.com/vmware-tanzu/velero/pull/7602
- https://github.com/zhuxiujia/GoMybatis/pull/75
- https://github.com/open2b/scriggo/issues/948
- https://github.com/spatial-go/geoos/pull/111
- https://github.com/vitessio/vitess/pull/16327

**Comment by ldez** [comment]
FYI the example you are using:
```go
for _, n := range ns {
   rs = append(rs, n)   
   rs = append(rs, ns...)
}
```

The 2 lines are wrong, in this context the right code is to remove the `for`:
```go
rs = append(rs, ns...)
```

A better example could be:

```
for _, n := range ns {
	if v == "value" {
		rs = append(rs, n)     // OK
		rs = append(rs, ns...) // Bug
	}
}
```
