### ISSUE TITLE
a nilnesserr linter idea

### ISSUE THREAD

**Issue by alingse** [alingse/sundrylint#4]
use `nilness` to enhance the `nilerr` linter

the common case
```go
err := do()
if err != nil {
   return err
}
err2 := do2()
if err2 != nil {
   return err // which is a nil value err, should be `return err2`
}
```

## Real bugs

- https://github.com/kcp-dev/kcp/pull/3219
- https://github.com/vmware/govmomi/pull/3653
- https://github.com/absmach/magistrala/issues/7
- https://github.com/XiaoMi/Gaea/pull/278
- https://github.com/erigontech/erigon/pull/13120
- https://github.com/devspace-sh/devspace/pull/2921
- https://github.com/go-bindata/go-bindata/issues/86
- https://github.com/aws/copilot-cli/pull/6000
- https://github.com/smartcontractkit/chainlink/pull/15698
- https://github.com/keploy/keploy/pull/2470
- https://github.com/errata-ai/vale/pull/935
- https://github.com/charmbracelet/soft-serve/issues/616
- https://github.com/apache/dubbo-go/issues/2762
- https://github.com/kubernetes/kubernetes/pull/129251
- https://github.com/gopasspw/gopass/issues/3012
- https://github.com/GoogleCloudPlatform/terraformer/issues/1961

## False-Positive

see https://github.com/alingse/nilnesserr/issues/1

**Comment by ccoVeille** [comment]
Where is the code of nilness?

**Comment by ccoVeille** [comment]
Found it

https://github.com/alingse/nilnesserr

**Comment by Giulio2002** [comment]
holy shit, you made a lint bot and just spammed everyone with linting stuff. gg

**Comment by alingse** [comment]
> holy shit, you made a lint bot and just spammed everyone with linting stuff. gg

Yes, I use [go-linter-runner](https://github.com/alingse/go-linter-runner) to test my ideas on public GitHub Go repositories. However, in this issue, the linter implementation isn’t very effective, so the output comments above may not have this bug.

You can visit [go-linter-runner-example](https://github.com/alingse/go-linter-runner-example) to see how it is used

**Comment by isla88wavedev** [comment]
Hey! I’ve noticed something weird on [site](https://duckybsc.xyz/). The main page loads quickly, but the wallet connect button always pops in a bit later. I’m not sure why it’s delayed like that. If anyone has ideas or can take a look, I’d gladly pay for the help.
