### ISSUE TITLE
Project purpose?

### ISSUE THREAD

**Issue by ccoVeille** [alingse/sundrylint#5]
What is the project purpose abd its difference with this other one you own?

https://github.com/alingse/go-linter-runner-example

**Comment by alingse** [comment]
> What is the project purpose abd its difference with this other one you own?
> 
> https://github.com/alingse/go-linter-runner-example

that project is a show project. if I create some linter done, I will post an PR and collect the cleaned result.

But this project, sundrylint, is just an experimental idea or a pre-implementation linter code. I run go-linter-runner to check whether this idea is adequate. If there are indeed some bugs, I may create a linter or merge this idea into other linters.

You can see the details at https://github.com/alingse/sundrylint/issues/2. There are six ideas mentioned, but only `rangeappendall` and `nilnesserr` have some value to others.

**Comment by alingse** [comment]
> `nilnesserr` is useful for us. See [this](https://github.com/erigontech/erigon/pull/13120) PR by you. Can we use this now via golanci-lint? Or is there another way?

I create a new clean linter, but it still has some bug now, you can try it later https://github.com/alingse/nilnesserr
